definitions:
  models.Data:
    properties:
      id:
        type: string
      name:
        type: string
    required:
    - name
    type: object
info:
  contact: {}
paths:
  /api/v1/data:
    get:
      consumes:
      - application/json
      description: get all data
      produces:
      - text/plain
      responses:
        "200":
          description: answer
          schema:
            type: string
        "400":
          description: ok
          schema:
            type: string
        "404":
          description: ok
          schema:
            type: string
        "500":
          description: ok
          schema:
            type: string
      summary: get request example
      tags:
      - example
    post:
      consumes:
      - application/json
      description: post request example
      parameters:
      - description: Sample data
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/models.Data'
      produces:
      - text/plain
      responses:
        "200":
          description: success
          schema:
            type: string
        "500":
          description: fail
          schema:
            type: string
      summary: post request example
swagger: "2.0"
